config/routes.rb
Rails.application.routes.draw do
  
  
  root 'homes#index'
  devise_for :users
  resources :metals
  resources :homes, only:[:index] do
    collection do 
      put 'update_metals'
      get 'diamond_values'
      put 'update_variants_value'
      get 'shopify_url'
      get 'set_shop'
      get 'metals_list'
      put 'update_shopify_url' 
      get 'sync'     
    end
  end

  resources :products do
    member do
      put 'update_metal_prices'
    end
    collection do
      get 'reload_products'     
    end
  end

  namespace :webhooks do
    post 'create_product'
    post 'update_product'
    post 'delete_product'
  end
end

app/models/metal.rb
class Metal < ActiveRecord::Base
  belongs_to :product
  #validates :price, numericality: { only_integer: true }
  validates_presence_of :price
  after_save :status_update

  def status_update
  	total = product.metals.count
  	filled = product.metals.where('price > ?', 0).count
  	unfilled = product.metals.where('price = ?', 0).count  
		if filled === total
  		product.update_attributes(:status => "all_filled")
		elsif filled < total && filled > 0
  		product.update_attributes(:status => "partially_filled")
		else
 			product.update_attributes(:status => "unfilled")
		end
	end
end

app/controllers/metals_controller.rb
class MetalsController < ApplicationController
  before_action :set_metal, only: [:show, :edit, :update, :destroy]

  # GET /metals
  # GET /metals.json
  def index
    @metals = Metal.includes(:product)
  end

  # GET /metals/1
  # GET /metals/1.json
  def show
  end

  # GET /metals/new
  def new
    @metal = Metal.new
  end

  # GET /metals/1/edit
  def edit     
    @product = Product.find(@metal.product.id)
    @api_product = ShopifyAPI::Product.find(@metal.product.prod_id)

    respond_to do |format|      
      format.js
    end
  end

  # POST /metals
  # POST /metals.json
  def create
    @metal = Metal.new(metal_params)

    respond_to do |format|
      if @metal.save
        format.html { redirect_to @metal, notice: 'Metal was successfully created.' }
        format.json { render :show, status: :created, location: @metal }
      else
        format.html { render :new }
        format.json { render json: @metal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metals/1
  # PATCH/PUT /metals/1.json
  def update
    respond_to do |format|
      if @metal.update(metal_params)
        @product = @metal.product
        @product.flag = false
        @product.save!
        format.html { redirect_to metals_url, notice: "'#{@metal.product.title}' product with metal '#{@metal.name}' was successfully updated." }
        format.json { render :show, status: :ok, location: @metal }
      else
        format.html { redirect_to metals_url, alert: "'#{@metal.product.title}' product with metal '#{@metal.name}' was failed to update." }
        format.json { render json: @metal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metals/1
  # DELETE /metals/1.json
  def destroy
    @metal.destroy
    respond_to do |format|
      format.html { redirect_to metals_url, notice: 'Metal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metal
      @metal = Metal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metal_params
      params.require(:metal).permit(:name, :price, :product_id)
    end
end

app/helpers/metals_helper.rb
module MetalsHelper
end

app/views/metals/_form.html.erb
<div class="modal-dialog"  style="top: 15em;">
  <div class="modal-content">
    <%= form_for(@metal) do |f| %>   
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title"><%= @metal.product.title %> with metal: <%= @metal.name %> </h4>
    </div>
    <div class="modal-body">
      <% if @metal.errors.any? %>
      <h5><%= pluralize(@metal.errors.count, "error") %> prohibited this metal from being saved:
      </h5>
      <% @metal.errors.full_messages.each do |message| %>
      <p><%= message %></p>
      <% end %>
      </p>
      </p>
      <% end %>
      <p><%= f.label :price %>: <%= f.text_field :price, class: "number" %></p>
    </div>
    <div class="modal-footer">
      <%= submit_tag 'Save Changes' , class: 'btn btn-danger cursor_wait' %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
    <% end %>
  </div>
</div>
<script src="http://code.jquery.com/jquery-latest.min.js"
  type="text/javascript"></script>
<script>
  $('.number').keypress(function(event) {
    if(event.which == 8 || event.keyCode == 37 || event.keyCode == 39 || event.keyCode == 46) 
      return true;
    else if((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57))
      event.preventDefault();
  });
</script>

app/views/metals/edit.html.erb
<h1>Editing metal </h1>

<%= render 'form' %>

<%= link_to 'Show', @metal %> |
<%= link_to 'Back', '/metals' %>

app/views/metals/edit.js.erb
$("#myModal").html("<%= j(render 'form') %>");

app/views/metals/index.html.erb
<h1>Listing Metals</h1>

<table id="almetals" class="table">
  <thead>
   
    <tr>
      
      <th>Product</th>
      <th>Metal Name</th>
      <th>Price</th>
      <th>Edit</th>
    </tr>
 
  </thead>

  <tbody>
  
    <% @metals.each do |metal| %>
      <tr>
        <td><%= metal.product.title %></td>
        <td><%= link_to metal.name, edit_metal_path(metal),remote: :true, "data-toggle" => "modal", 'data-target' => '#myModal' %></td>
        <td><%= metal.price %></td>
        <td><%= link_to 'Edit',  edit_metal_path(metal),remote: :true, "data-toggle" => "modal", 'data-target' => '#myModal'  %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>
<div id="testmodal">

</div>
<div id="myModal" class="modal fade" role="dialog">


    <!-- Modal content-->
    

</div>

app/views/metals/new.html.erb
<h1>New Metal</h1>

<%= render 'form' %>

<%= link_to 'Back', metals_path %>

app/views/metals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @metal.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @metal.price %>
</p>

<p>
  <strong>Product:</strong>
  <%= @metal.product.title %>
</p>

<%= link_to 'Edit', edit_metal_path(@metal) %> |
<%= link_to 'Back', metals_path %>