config/routes.rb
Rails.application.routes.draw do
  
  
  root 'homes#index'
  devise_for :users
  resources :metals
  resources :homes, only:[:index] do
    collection do 
      put 'update_metals'
      get 'diamond_values'
      put 'update_variants_value'
      get 'shopify_url'
      get 'set_shop'
      get 'metals_list'
      put 'update_shopify_url' 
      get 'sync'     
    end
  end

  resources :products do
    member do
      put 'update_metal_prices'
    end
    collection do
      get 'reload_products'     
    end
  end

  namespace :webhooks do
    post 'create_product'
    post 'update_product'
    post 'delete_product'
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :check_shop, :except => [:set_shop, :update_metals]
  
  def index
    
  end

  def update_metals
    count = params[:ids].count
    count.times do |x|
      @metal = Variant.find(params[:ids][x])
      @metal.update_attributes(:metal_price => params[:metal_prices][x])
    end
    redirect_to root_path, notice: 'Metal updated.' 
  end
  
  def diamond_values
    gemstone_list = Gemstone.all
    @gemstones = gemstone_list.uniq
    if @gemstones.present?
      $alrtb = 0    
    end
    $alrtbb = $alrtbb + 1 if $alrtbb  
  end

  def sync
    Gemstone.delete_all    
    Gemstone.delay.synchronization
    $alrtb = 1
    redirect_to diamond_values_homes_path
  end

  def update_variants_value
    alert = 1
    params[:prices].each { |price| alert = 0 if price == '0' }
    if alert == 0
      flash[:notice] = "Please set the valid price, not 0"
      redirect_to diamond_values_homes_path
    else
      Variant.delay.update_variants_value(params,current_user.email)
      $alrtbb = 1
      redirect_to diamond_values_homes_path
    end  
  end
  
  def set_shop    
    if Shop.last
      @shop_link_kr = Shop.last.url
    else      
      flash[:notice] = "Please set the correct shop url"
    end
  end

  def shopify_url
  end

  def update_shopify_url
    url = params[:url]
    Shop.create(:url => url)
    ShopifyAPI::Base.clear_session
    shop_url = Shop.last.url
    ShopifyAPI::Base.site = shop_url
    redirect_to shopify_url_homes_path, notice: 'SHOP URL successfully updated.'
  end
 
  def metals_list
    @total_products = ShopifyAPI::Product.count
    @total_pages = (@total_products / 250.0).ceil
    @products = []
    @total_pages.times do |x|
      page = x+1
      @products += ShopifyAPI::Product.find(:all, :params => {:limit => 250, :page => page})
    end
    variants = Variant.all
    metals_list = []
    @products.each do |product|
      if product.options.first.name == 'Metal'
          metals = product.options.first.values
          metals.each do |metal_title|
          metals_list << metal_title.downcase
          end           
      end
    end
    @metals = metals_list.uniq
    if variants.blank?
        @metals.each do |metal_title|
           Variant.create(:metal_title => metal_title)
        end
    end
    @a=Variant.pluck(:metal_title)
    unless @metals & @a == @metals
      old_metal = @a - @metals
      if old_metal.present?
        Variant.find_by_metal_title(old_metal.first).destroy
      end
      new_metal = @metals - @a
      if new_metal.present?
        Variant.create(:metal_title => new_metal.first) 
      end
    end
    @variants = Variant.all
  end

  def products
    
  end

 private

 def check_shop
  if Shop.first.nil?
    #Shop.create(:url => "https://3c33cb8a597561c457dd429d9ef72fc8:1c2753c8811b76262ccc6aa3f27dda9f@bylu.myshopify.com/admin")
    Shop.create(:url => "https://5000b6fab6a48677813d80080e505c18:1eebe1b232ede28bfa0e68c673a317d7@rormobikasa.myshopify.com/admin")
    ShopifyAPI::Base.site = Shop.last.url
  else
    shop_url = Shop.last.url
    ShopifyAPI::Base.site = shop_url
  end
 end
 
end

app/views/homes/diamond_values.html.erb
<% if $alrtb == 1 %>
<div class="alert alert-warning alert-dismissible">
  <i class="fa fa-ban"></i>
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <b><%= "Synchronizing all metals gemstones from Shopify shop, It will take time. Please refresh page after 1 minute." %></b>
</div>
<% end %>
<% if $alrtbb && $alrtbb <= 2 %>
<div class="alert alert-warning alert-dismissible">
  <i class="fa fa-ban"></i>
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <b><%= "Updateing variant's price on Shopify shop, It will take time. Please refresh page after 1 minute." %></b>
</div>
<% end %>
<%#= link_to "Synchronization", sync_homes_path %>
<a href="/homes/sync" role="button" class="btn btn-success btn-large">Synchronization</a>
<!-- <a href="/homes/sync" class="btn btn-primary" role="button">Synchronization</a> -->
<%= form_tag '/homes/update_variants_value', :method => 'put', :class => "form-inline" do %>
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Update in Shopify According to Product's Metal Price</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body no-padding">
    <table class="table table-striped">
      <thead>
        <tr>
          <th style="width: 10px">#</th>
          <th>Diamond</th>
          <th>Current Price</th>
          <th>New Price</th>
        </tr>
      </thead>
      <tbody>
        <div class="list">
          <% @gemstones.each_with_index do |gemstone, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= gemstone.name %></td>
            <td><%= gemstone.price %></td>
            <td><%= text_field_tag 'prices[]', nil, placeholder: "Enter new price..", class: "form-control number" %>
              <%= hidden_field_tag 'gemstones[]', gemstone.name %>
            </td>
          </tr>
          <% end %>
        </div>
      </tbody>
    </table>
  </div>
  <!-- /.box-body -->
</div>
<%= submit_tag 'Update Product Prices', 'data-disable-with' => "Please wait..", class: 'btn btn-warning' %></td></tr>
<% end %>
<script src="http://code.jquery.com/jquery-latest.min.js"
  type="text/javascript"></script>
<script>
  $('.number').keypress(function(event) {
    if(event.which == 8 || event.keyCode == 37 || event.keyCode == 39 || event.keyCode == 46) 
      return true;
    else if((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57))
      event.preventDefault();
  });
</script>

app/views/homes/index.html.erb
<div class="row">
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3><%= @total = Product.count %></h3>

              <p>Total Products</p>
            </div>
            <div class="icon">
              <i class="ion ion-bag"></i>
            </div>
            <a href="/products" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3><%= @unfilled = Metal.where('price = ?', 0).select(:product_id).uniq.count %><sup style="font-size: 20px"></sup></h3>

              <p>Unfilled products</p>
            </div>
            <div class="icon">
              <i class="ion ion-stats-bars"></i>
            </div>
            <a href="/products" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3><%= @total-@unfilled%></h3>

              <p>Filled Products</p>
            </div>
            <div class="icon">
              <i class="ion ion-android-list"></i>
            </div>
            <a href="/products" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
     <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3><%= Product.where(:status => "partially_filled").count %></h3>

              <p>Partially Filled</p>
            </div>
            <div class="icon">
              <i class="ion ion-pie-graph"></i>
            </div>
            <a href="/products" class="small-box-footer">
              More info <i class="fa fa-arrow-circle-right"></i>
            </a>
          </div>
        </div>
      </div>

app/views/homes/metals_list.html.erb
<%= form_tag('/homes/update_metals', method: :put) do %>
<h3>Listing Metals</h3>
<table id="products" class="table table-striped table-bordered" cellspacing="0" width="90%">
  <thead>
    <tr>
      <th>Metal title</th>
      <th>Metal price</th>
    </tr>
  </thead>
  <tbody>
    <% @variants.each do |variant| %>
    <tr>
      <td><%= variant.metal_title %></td>
      <td><%= text_field_tag 'metal_prices[]', variant.metal_price %></td>
        <%= hidden_field_tag 'ids[]', variant.id %>      
    </tr>
    <% end %>
    <tr><td></td>
      <td><%= submit_tag 'Save Changes' , class: 'btn btn-danger' %></td>
    </tr>
  </tbody>
</table>
  
<% end %>

app/views/homes/set_shop.html.erb
<h4>Shopify Store URL Setup</h4></br>
<% if @shop_link_kr %>
  <p><b style="color:#3c8dbc;">Current Shopify Store URL:</b> <b style="color:green;"><%= @shop_link_kr %></b></p>
<% else %>
  <p>Currently No Any Shopify Store URL Found.</p>
<% end %></br>
<%= form_tag '/homes/update_shopify_url', :method => 'put', :class => "form-inline" do %>
<div class="form-group">
   <%= text_field_tag :url, params[:query], placeholder: "https://5000b6fab6a48677813d80080e505c18:1eebe1b232ede28bfa0e68c673a317d7@shopname.myshopify.com/admin", :size=>"130", class: "form-control"%>
</div>
<button type="submit" class="btn btn-warning">Update URL</button>
<% end %>
<br />
 

app/views/homes/shopify_url.html.erb
<h4>Currently we are using <%= ShopifyAPI::Shop.current.name %> </h4></br>
<%= form_tag '/homes/update_shopify_url', :method => 'put', :class => "form-inline" do %>
<div class="form-group">
   <%#= text_field_tag :query_1, params[:query], placeholder: "Enter gemstone", class: "form-control"%>
   <%= text_field_tag :url, params[:query], placeholder: "Enter new url..", :size=>"130", class: "form-control"%>
</div>
<button type="submit" class="btn btn-warning">Update URL</button>
<% end %>
<br />
 