config/routes.rb
Rails.application.routes.draw do
  
  
  root 'homes#index'
  devise_for :users
  resources :metals
  resources :homes, only:[:index] do
    collection do 
      put 'update_metals'
      get 'diamond_values'
      put 'update_variants_value'
      get 'shopify_url'
      get 'set_shop'
      get 'metals_list'
      put 'update_shopify_url' 
      get 'sync'     
    end
  end

  resources :products do
    member do
      put 'update_metal_prices'
    end
    collection do
      get 'reload_products'     
    end
  end

  namespace :webhooks do
    post 'create_product'
    post 'update_product'
    post 'delete_product'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :metals, :dependent => :destroy
    has_many :variant_backups, :dependent => :destroy
	#has_many :gemstones, :dependent => :destroy

	accepts_nested_attributes_for :metals, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
	#accepts_nested_attributes_for :gemstones, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

    def self.get_all_metal_products
      ShopifyAPI::Base.site = Shop.last.url

      @total_products = ShopifyAPI::Product.count
      @total_pages = (@total_products / 250.0).ceil

      @products = []
      @total_pages.times do |x|
        page = x+1
        @products += ShopifyAPI::Product.find(:all, :params => {:limit => 250, :page => page})
      end
      
      @products.each do |product|
        if product.options.first.name == 'Metal'
          element = Product.new
          element.title = product.title
          element.product_type = product.product_type
          element.prod_id = product.id
          product.options.first.values.each do |title|
              element.metals.build(:name => title.downcase ,:price => 0)
          end 
          # if product.options.last.name == 'Gemstone'
          #   product.options.last.values.each do |title|
          #     element.gemstones.build(:name => title ,:price => 0)
          #   end 
          # end
          # product.variants.each do |var|
          #  element.metals.build(:name => var.option1, :gemstone => var.option2, :price => 0)
          # end      
          element.save!           
        end      
      end

      # webhooks = ShopifyAPI::Webhook.all
      # webhooks.each do |x|
      #   x.destroy
      # end
      # update_webhook = ShopifyAPI::Webhook.new({:topic => "products/update", :address => "http://rorapp.mobikasa.com/webhooks/update_product", :format => "json"})
      # update_webhook.save!
      # create_webhook = ShopifyAPI::Webhook.new({:topic => "products/create", :address => "http://rorapp.mobikasa.com/webhooks/create_product", :format => "json"})
      # create_webhook.save!
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create_product]
  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :check_shop, :except => [:set_shop, :update_metals]

  # GET /products
  # GET /products.json
  def index    
    products = Product.all
    if products.blank?
      $globl = 0 if $globl == nil
      @alert_msg = 'Fetching all products from Shopify shop, It will take time. Please refresh page after 1 minute.'
      if $globl == 0      
        Product.delay.get_all_metal_products       
      end  
      $globl = 1 
    end    
    @products = Product.includes(:metals)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    
    @product = Product.find(params[:id])
    @api_product = ShopifyAPI::Product.find(@product.prod_id)
       
    metals_list = []    

    if @api_product.options.first.name == 'Metal'
      metals = @api_product.options.first.values
      metals.each do |metal_title|
        metals_list << metal_title.downcase
      end           
    end
   
    @metals = metals_list.uniq    
    metals = @product.metals
    if metals.blank?
        @metals.each do |metal_title|
           Metal.create(:name => metal_title, :product_id => @product.id)
        end
    end

    @a = Metal.where(:product_id => @product.id).pluck(:name)
    
    #if @metals & @a == @metals
      old_metal = @a - @metals
      if old_metal.present?
        old_metal.each do |x|             
          @product.metals.find_by_name(x).destroy
        end
      end
    #end

    #unless @metals & @a == @metals
      new_metal = @metals - @a     
      if new_metal.present?
        new_metal.each do |y|          
          @product.metals.build(:name => y, :price => '0').save! 
        end
      end
    #end
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
  end


  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update_metal_prices
    @product = Product.find(params[:id])
    params[:ids].each_with_index do |metal_id, index|
      @variant = @product.metals.find(metal_id)
      @variant.price = params[:prices][index]
      @variant.save!
    end
    @product.flag = false
    @product.save!
    redirect_to @product, notice: 'Product was successfully updated.' 
  end

  def reload_products
    Product.destroy_all

    webhooks = ShopifyAPI::Webhook.all
    webhooks.each do |x|
      x.destroy
    end
   
    redirect_to products_path, notice: 'Product was successfully Reloaded.' 
  end

   
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :product_type, )
    end

    def metal_params
      params.require(:metal).permit(:name, :price)
    end

    def check_shop
      if Shop.first.nil?
        #Shop.create(:url => "https://3c33cb8a597561c457dd429d9ef72fc8:1c2753c8811b76262ccc6aa3f27dda9f@bylu.myshopify.com/admin")
        Shop.create(:url => "https://5000b6fab6a48677813d80080e505c18:1eebe1b232ede28bfa0e68c673a317d7@rormobikasa.myshopify.com/admin")
        ShopifyAPI::Base.site = Shop.last.url
      else
        shop_url = Shop.last.url
        ShopifyAPI::Base.site = shop_url
      end
    end
 
end

app/helpers/products_helper.rb
module ProductsHelper
	def verify_webhook(data, hmac_header)
    digest  = OpenSSL::Digest::Digest.new('sha256')
    calculated_hmac = Base64.encode64(OpenSSL::HMAC.digest(digest, 'e9a934c972bea1863238150e17f7cc0bd849e870280ae2cd7694b47133092640', data)).strip
    calculated_hmac == hmac_header
  end
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" } do |f| %>

    <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :product_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :product_type, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:product_type]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            products_path, :class => 'btn btn-default' %>

<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<% if @alert_msg %>
<div class="alert alert-warning alert-dismissible">
  <i class="fa fa-ban"></i>
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <b><%= @alert_msg %></b>
</div>
<% end %>        
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table  id="products" class="table">
  <thead>
    <tr>   
      <th><%= model_class.human_attribute_name(:list) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>      
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>        
        <td><%= link_to product.title, product_path(product) %></td>
        <td><%= product.status %></td>             
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<style>
  .empty{ background-color: #01A9DB;}
  .filled{ background-color: #CCFFCC;}
</style>
<% content_for :back do %>
<li><%= link_to t('.back', :default => t("helpers.links.back")),
  products_path %></li>
<% end %>
<%= form_tag(update_metal_prices_product_path, method: :put) do %>
<h1 style="font-variant: small-caps;"><%= @product.title%>'s metals</h1>
<table id="metals" class="table">
  <thead>
    <tr>
      <th>Metal Name</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @product.metals.each do |metal| %>
    <tr>
      <td><%= metal.name %></td>
      <td><%= text_field_tag 'prices[]', metal.price, class: "number" %></td>
      <%= hidden_field_tag 'ids[]', metal.id %>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to t('.back', :default => t("helpers.links.back")),
  products_path, :class => 'btn btn-default cursor_wait'  %>
<%= submit_tag 'Save Changes', 'data-disable-with' => "Please wait..", class: 'btn btn-danger submit' %>
<% end %>
<script src="http://code.jquery.com/jquery-latest.min.js"
  type="text/javascript"></script>
<script>
  $('.number').keypress(function(event) {
    if(event.which == 8 || event.keyCode == 37 || event.keyCode == 39 || event.keyCode == 46) 
      return true;
    else if((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57))
      event.preventDefault();
  });
</script>