config/routes.rb
Rails.application.routes.draw do
  
  
  root 'homes#index'
  devise_for :users
  resources :metals
  resources :homes, only:[:index] do
    collection do 
      put 'update_metals'
      get 'diamond_values'
      put 'update_variants_value'
      get 'shopify_url'
      get 'set_shop'
      get 'metals_list'
      put 'update_shopify_url' 
      get 'sync'     
    end
  end

  resources :products do
    member do
      put 'update_metal_prices'
    end
    collection do
      get 'reload_products'     
    end
  end

  namespace :webhooks do
    post 'create_product'
    post 'update_product'
    post 'delete_product'
  end
end

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<% if user_signed_in? %>
<header class="main-header">
  <!-- Logo -->
  <a href="/" class="logo cursor_wait">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>K</b>DD</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Ken & Dana Design</b></span>
  </a>
  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
    <span class="sr-only">Toggle navigation</span>
    </a>
    <ul class="nav navbar-nav">
            <%= yield :back%>
        </ul>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <!-- Notifications Menu -->
        <!-- Tasks Menu -->
        <!-- User Account Menu -->
        <li >
          <!-- Menu Toggle Button -->
          
          <a class="navbar-nav"><%= current_user.email %></a>
          
        
        </li>
        <li>
          <%= link_to " Logout", destroy_user_session_path, class: 'fa glyphicon glyphicon-log-out' %>
        </li>
      </ul>
    </div>
  </nav>
</header>
<% end %>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<% if user_signed_in? %>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
   
    <ul class="sidebar-menu">
      <li class="header"><%#= ShopifyAPI::Shop.current.name %> </li>
      <!-- Optionally, you can add icons to the links -->
      <li class="<%= is_active?('/homes/index') %>"><a href="/homes"><i class='fa glyphicon glyphicon-equalizer'></i> <span>Home</span></a></li>
      <li id="product_b" class="<%= is_active?('/products') %>"><a href="/products" class="cursor_wait"><i class='fa glyphicon glyphicon-modal-window'></i> <span>Products</span></a></li>           
      <li id="metal_b" class="<%= is_active?('/metals') %>"> <a href="/metals"><i class='fa glyphicon glyphicon-circle-arrow-down'></i> <span>All Metals</span></a></li> 
      <!-- 
      <li><a href="/variants"><i class='fa glyphicon glyphicon-equalizer'></i> <span>Diamond Variant Products</span></a></li>
      <li><a href="/update_variants"><i class='fa glyphicon glyphicon-equalizer'></i> <span>Update Variants Title</span></a></li> -->
      <li id="diamond_b" class="<%= is_active?('/homes/diamond_values') %>"><a href="/homes/diamond_values" class="cursor_wait"><i class='fa glyphicon glyphicon-equalizer '></i> <span>Update Diamond Value</span></a></li>
      <li class="<%= is_active?('/homes/set_shop') %>"><a href="/homes/set_shop"><i class='fa glyphicon glyphicon-circle-arrow-down'></i> <span>Set Store URL</span></a></li>
      <!--<li><a href="/homes/shopify_url" class="cursor_wait"><i class='fa glyphicon glyphicon-th'></i> <span>Change Shop</span></a></li>
      <li><a href="/update_variants_price"><i class='fa glyphicon glyphicon-equalizer'></i> <span>Update Variants Title Value</span></a></li> -->
      <!-- <li class="treeview">
        <a href="#"><i class='fa fa-link'></i> <span>More</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="/">Orders</a></li>
          <li><a href="#">Others</a></li>
        </ul>
        </li> -->
    </ul>
    <!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <!-- To the right -->
  <div class="pull-right hidden-xs">
    <span title="<%#= @shop_link_kr %>">All Rights Reserved.</span>
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2015 <a href="http://www.mobikasa.com">Mobikasa Inc.</a></strong> 
</footer>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Ken & Dana Design</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" /> 
   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <script src='/assets/nprogress.js'></script>
    <link rel='stylesheet' href='/assets/nprogress.css'/>
    <style>
      .unfilled {
          background-color: #E7C39C;
      }

    .partially_filled {
        background-color: #E7DF9C;
      }

      .populated {
          background-color: #EFEBD6;
      }
    </style>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
  </head>
  <body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
    <div class="wrapper">
      <%= render partial: 'layouts/admin_lte_2_header' %>
      <%= render partial: 'layouts/admin_lte_2_sidebar' %>
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <section class="content">
          <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= notice %></b>
          </div>
          <% end %>
          <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
          <% end %>
          <%= yield %>
        </section>
        <!-- /.content -->
      </div>
      <%= render 'layouts/footer' %>
      <div class="control-sidebar-bg" style="position: fixed; height: auto;"></div>
    </div>
    <!-- ./wrapper -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Ken & Dana Design | Log in</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
  </head>
  <body class="login-page">
    <% if notice %>
    <div class="alert alert-success alert-dismissable">
      <i class="fa fa-check"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <b><%= notice %></b>
    </div>
    <% end %>
    <% if alert %>
    <div class="alert alert-danger alert-dismissable">
      <i class="fa fa-ban"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <b><%= alert %></b>
    </div>
    <% end %>
    <div class="login-box">
      <div class="login-logo">
        <b>Ken & Dana Design</b>
      </div>
      <!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="form-group has-feedback">
          <%= f.text_field :email, class: 'form-control', autofocus: true %>
          <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
          <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <div class="row">
          <div class="col-xs-4">
            <%= f.submit 'Log in', class: 'btn btn-primary btn-block btn-flat' %>
            <!-- <a href="/users/sign_up">Sign up</a> -->
          </div>
          <!-- /.col -->
        </div>
        <% end %>
      </div>
      <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ken & Dana Design</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>